version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env  # Используем переменные из файла .env

  redis:
    image: redis:alpine

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env  # Используем переменные из файла .env
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A lms_project worker --loglevel=info
    volumes:
      - .:/usr/src/app
    env_file:
      - .env  # Используем переменные из файла .env
    depends_on:
      - web
      - redis

  celerybeat:
    build: .
    command: celery -A lms_project beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/usr/src/app
    env_file:
      - .env  # Используем переменные из файла .env
    depends_on:
      - web
      - redis

volumes:
  postgres_data:
