version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=lms_db
      - POSTGRES_USER=lms_user
      - POSTGRES_PASSWORD=lms_password

  redis:
    image: redis:alpine

  web:
    build: ./lms_project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./lms_project:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=lms_db
      - DB_USER=lms_user
      - DB_PASS=lms_password
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery:
    build: ./lms_project
    command: celery -A lms_project worker --loglevel=info
    volumes:
      - ./lms_project:/usr/src/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - web
      - redis

volumes:
  postgres_data:
